fix(train_prometheus_checker): Fixed Prometheus Checker
Fixed checker to determine if the endpoints are reachable or not
after 10 attempts. As soon as the endpoints are reachable, the checks
continue successfully, otherwise they fail.

Signed-off-by: Kaiyi <kaiyiliu21@gmail.com>

diff --git a/.github/actions/train-action/action.yml b/.github/actions/train-action/action.yml
--- a/.github/actions/train-action/action.yml
+++ b/.github/actions/train-action/action.yml
@@ -11,22 +11,47 @@ runs:
     - name: Check Prometheus Endpoint
       shell: bash
       run: |
+        success=false
         for i in {1..10}; do
+          echo "Attempt $i"
           status_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:9090)
           if [ "$status_code" -ne 200 ]; then
             echo "Prometheus Endpoint is inactive (status: $status_code)"
-            exit 1
+            sleep 10
           else
             echo "Prometheus Endpoint is active"
+            success=true
+            break
           fi
+        
+        done
 
-          metric_response = $(curl -sG http://localhost:9090/api/v1/query --data-urlencode 'query=kepler_process_bpf_cpu_time_ms_total{job="vm"}')
+        if [ "$success" = false ]; then
+          echo "Failed to reach Prometheus Endpoint after 10 attempts"
+          exit 1
+        fi
+
+    - name: Check Prometheus VM Target Metric
+      shell: bash
+      run: |
+        success=false
+        for i in {1..10}; do
+          echo "Attempt $i"
+          metric_response=$(curl -sG http://localhost:9090/api/v1/query --data-urlencode 'query=kepler_container_bpf_cpu_time_ms_total{job="vm"}')
           if echo "$metric_response" | grep -q '"result":\[\]'; then
             echo "Target VM Metric does not exist or is empty"
-            exit 1
+            sleep 10
           else
             echo "Target VM Metric does exist and is nonempty"
+            success=true
+            break
           fi
+        done
+
+        if [ "$success" = false ]; then
+          echo "Failed to reach Target VM Metric after 10 attempts"
+          exit 1
+        fi
 
     - name: Train models
       shell: bash
