Fix equinix_k8s_trainer.yml

diff --git a/.github/workflows/equinix_k8s_trainer.yml b/.github/workflows/equinix_k8s_trainer.yml
--- a/.github/workflows/equinix_k8s_trainer.yml
+++ b/.github/workflows/equinix_k8s_trainer.yml
@@ -32,8 +32,75 @@ permissions:
 
 
 jobs:
+  Create-k8s-cluster:
+    name: "Create Cluster"
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Validate termination time
+        run: |
+          if [ ${{ github.event.inputs.termination_time || '1' }} -gt 48 ]; then
+            echo "Error: Termination time cannot be more than 48 hours."
+            exit 1
+          fi
+
+      - name: Install ansible, git and jq
+        run: |
+          sudo apt-get update
+          sudo apt-get install ansible jq git -y
+
+      - name: Clone repo
+        run: |
+          cd ~
+          git clone https://github.com/sustainable-computing-io/kepler-metal-ci
+
+      - name: Save ssh key from env to file
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.EQUINIX_SSH_KEY }}" > ~/.ssh/kepler_ci
+          chmod 600 ~/.ssh/kepler_ci
+          echo "StrictHostKeyChecking no" >> ~/.ssh/config
+
+      - name: Create metal config
+        run: |
+          cat <<EOF > /tmp/metal.yaml
+          token: "${{ secrets.METAL_AUTH_TOKEN }}"
+          project-id: ${{ secrets.EQUINIX_PROJECT_ID }}
+          EOF
+
+      - name: Play k8s_kubeadm.yml
+        env:
+          metro: "da"
+          plan: "c3.small.x86"
+          os: "rhel_9"
+        run: |
+          mkdir -p ~/.ansible
+          echo '[defaults]' > ~/.ansible/ansible.cfg
+          echo 'callback_plugins = ~/.github/callback_plugins' >> ~/.ansible/ansible.cfg
+          echo 'callback_whitelist = mask_ip_callback' >> ~/.ansible/ansible.cfg
+          mkdir -p ~/.github/callback_plugins
+          cd ~/kepler-metal-ci
+          cp ansible/mask_ip_callback.py ~/.github/callback_plugins/mask_ip_callback.py
+          # save input var into extra-vars.yaml
+          echo "termination_time: ${{ github.event.inputs.termination_time || '1' }}" > /tmp/extra-vars.yaml
+          echo "control_plan: ${{ github.event.inputs.control_plan || 'c3.small.x86' }}" >> /tmp/extra-vars.yaml
+          echo "node_plan: ${{ github.event.inputs.node_plan || 'c3.small.x86' }}" >> /tmp/extra-vars.yaml
+          echo "metro: ${{ github.event.inputs.metro || 'da' }}" >> /tmp/extra-vars.yaml
+          ansible-playbook ansible/k8s_kubeadm.yml \
+            --extra-vars "@/tmp/extra-vars.yaml" 2>&1 >> k8s_kubeadm.log
+          sudo cat /tmp/kubeconfig |jq -r '.stdout' > /tmp/k8sconfig
+          sudo mv /tmp/k8sconfig /tmp/kubeconfig
+
+      - name: Upload kubeconfig
+        uses: actions/upload-artifact@v2
+        with:
+          name: kubeconfig-${{ github.run_id }}
+          path: /tmp/kubeconfig
+          retention-days: 1
+
   Test-K8s:
     name: "Test K8s"
+    needs: Create-k8s-cluster
     runs-on: ubuntu-latest
 
     env:
@@ -53,7 +120,7 @@ jobs:
       - name: Download kubeconfig
         uses: actions/download-artifact@v2
         with:
-          name: kubeconfig-10041599148
+          name: kubeconfig-${{ github.run_id }}
           path: ~/.kube/
 
       - name: Test k8s
@@ -146,7 +213,7 @@ jobs:
           kubectl apply -f ~/${TEKTON_PATH}/pipelines
 
       - name: Run Complete Training
-        run: kubectl apply -f ${TEKTON_PATH}/examples/single-train/abs-power.yaml
+        run: kubectl apply -f ~/${TEKTON_PATH}/examples/single-train/abs-power.yaml
       
       - name: Wait for Tekton Training
         run: |
