test kepler
Signed-off-by: Huamin Chen <hchen@redhat.com>

diff --git a/.github/workflows/equinix_metal_flow.yml b/.github/workflows/equinix_metal_flow.yml
--- a/.github/workflows/equinix_metal_flow.yml
+++ b/.github/workflows/equinix_metal_flow.yml
@@ -23,6 +23,7 @@ jobs:
     name: "Install"
     needs: Create-runner
     runs-on: self-hosted
+    continue-on-error: true
     outputs:
       runner-name: ${{ runner.name }}
 
@@ -77,6 +78,61 @@ jobs:
             become: true
           EOF
           ansible-playbook -i inventory.yml metrics.yml
+
+          set -o pipefail
+          set -e
+          # install podman
+          sudo dnf -y install podman
+          # wget kepler systemd unit file and save it to /etc/systemd/system/kepler.service
+          sudo wget https://raw.githubusercontent.com/sustainable-computing-io/kepler/main/packaging/rpm/container-kepler.service -O /etc/systemd/system/container-kepler.service
+          # start kepler service
+          sudo systemctl daemon-reload
+          sudo systemctl enable --now container-kepler
+          # curl kepler port 8888 with 10 seconds timeout and retry 5 times; if it fails, exit with error
+          for i in {1..5}; do 
+            echo "Attempt $i"
+            curl -s -o /dev/null http://localhost:8888 --connect-timeout 10
+            if [ $? -eq 0 ]; then 
+              break 
+            fi
+            sleep 5
+          done
+          if [ $? -ne 0 ]; then 
+            echo "Kepler did not start in time"
+            exit 1
+          fi
+          # dump kepler metrics
+          echo "Kepler started successfully, now dumping metrics"
+          curl -s http://localhost:8888/metrics |grep ^kepler_
+          # install openmetrics
+          echo "Installing openmetrics"
+          sudo yum install pcp-pmda-openmetrics -y
+          cd /var/lib/pcp/pmdas/openmetrics/; sudo echo "http://localhost:8888/metrics" > config.d/kepler.url; sudo ./Install
+          # validate kepler metrics
+          echo "Validating kepler metrics"
+          pminfo openmetrics |grep kepler
+          pmrep -s 10 openmetrics.kepler.kepler_node_package_joules_total
+          # create kepler pmlogger config
+          sudo mkdir -p /etc/pcp/pmlogconf/kepler
+          echo "Creating kepler pmlogger config"
+          cat > /etc/pcp/pmlogconf/kepler/kepler << EOF
+          #pmlogconf-setup 2.0
+          ident	 metrics used by the kepler node
+          probe	 openmetrics.kepler.kepler_node_package_joules_total
+            openmetrics.kepler.kepler_node_package_joules_total
+            openmetrics.kepler.kepler_node_dram_joules_total
+            openmetrics.kepler.kepler_node_core_joules_total
+          EOF
+          pmlogconf -r -g kepler /etc/pcp/pmlogconf/kepler/kepler
+          # start pmlogger
+          sudo systemctl restart pmlogger
+          sudo systemctl restart pmproxy
+          # check pmseries after 10 seconds
+          sleep 10
+          pmseries openmetrics.kepler.kepler_node_package_joules_total
+          # check the pmproxy metrics query
+          echo "Checking the pmproxy metrics query"
+          curl "http://localhost:44322/metrics?names=openmetrics.kepler.kepler_node_package_joules_total"
 
   Cleanup:
     name: "Cleanup"
